p1_compile:
	@echo compiling the greedy algorithm P1
	g++ -O2 -std=c++11 p1.cpp -o p1_greedy.bin

p1_test:
	@echo executing the greedy algorithm P1
	./p1_greedy.bin

p2_compile:
	@echo compiling the greedy algorithm P2
	g++ -O2 -std=c++11 p2.cpp -o p2_greedy.bin

p2_test:
	@echo executing the greedy algorithm P2
	./p2_greedy.bin

p3_compile:
	@echo compiling the greedy algorithm P3
	g++ -O2 -std=c++11 p3.cpp -o p3_greedy.bin

p3_test:
	@echo executing the greedy algorithm P3
	./p3_greedy.bin

p4_compile:
	@echo compiling the greedy algorithm P4
	g++ -O2 -std=c++11 p4.cpp -o p4_greedy.bin

p4_test:
	@echo executing the greedy algorithm P4
	./p4_greedy.bin

p5_compile:
	@echo compiling the greedy algorithm P5
	g++ -O2 -std=c++11 p5.cpp -o p5_greedy.bin

p5_test:
	@echo executing the greedy algorithm P5
	./p5_greedy.bin

all: p1_compile p1_test p2_compile p2_test p3_compile p3_test p4_compile p4_test p5_compile p5_test

clean:
	@rm -f *.bin
